[package]
name = "agatedb"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
bytes = "0.5"
crc = "1.8"
rand = "0.7"
proto = { path = "proto" }
skiplist = { path = "skiplist" }
memmap = "0.7"

[workspace]
members = [
    "proto",
    "skiplist",
]