[package]
name = "agatedb"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
bytes = "0.5"
rand = "0.7"
proto = { path = "proto" }
skiplist = { path = "skiplist" }
table = { path = "table" }
common = { path = "common" }
memmap = "0.7"
farmhash = "1.1"
prost = "0.6"

[workspace]
members = [
    "proto",
    "skiplist",
    "table",
    "common"
]
